set -g allow-passthrough all
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

source ~/.config/tmux/themes/jellybeans.tmux

# ── Plugins ───────────────────────────────────────────────────────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# ── tmux-resurrect ────────────────────────────────────────────────────────────
set -g @resurrect-capture-pane-contents 'on'

# ── tmux-continuum ────────────────────────────────────────────────────────────
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# ── Initialize TPM (must be last line) ───────────────────────────────────────
run '~/.tmux/plugins/tpm/tpm'
