set -g allow-passthrough all
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -g renumber-windows

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

#Binds
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -U
bind -n M-k select-pane -D

bind -n M-S-l next-window
bind -n M-S-h previous-window

bind -n M-p display-popup -w 80% -h 80% -E

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'dracula/tmux'
set -g @plugin 'hiroppy/tmux-agent-sidebar'

# Dracula status bar
set -g @dracula-plugins 'git cwd cpu-usage ram-usage ssh-session time'
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-refresh-rate 5
set -g @dracula-show-empty-plugins false

# # Jellybeans palette
# set -g @dracula-colors "
# white='#e8e8d3'
# gray='#4e4e4e'
# dark_gray='#303030'
# light_purple='#c6b6ee'
# dark_purple='#8787af'
# cyan='#8fbfdc'
# green='#99ad6a'
# orange='#ffb964'
# red='#cf6a4c'
# pink='#f0a0c0'
# yellow='#fad07a'
# "
# set -g @dracula-colors "
# # simple gruvbox Color Pallette
# white='#EBDBB2'
# gray='#32302F'
# dark_gray='#282828'
# light_purple='#B16286'
# dark_purple='#504945'
# cyan='#689D6A'
# green='#98971A'
# orange='#D65D0E'
# red='#CC241D'
# pink='#D3869B'
# yellow='#D79921'
# "
# set -g @dracula-colors "
# # simple catppuccin Color Pallette
# pink='#cba6f7'
# orange='#fab387'
# yellow='#f9e2af'
# green='#a6e3a1'
# cyan='#89dceb'
# light_purple='#b4befe'
# white='#cdd6f4'
# dark_gray='#313244'
# red='#f38ba8'
# gray='#45475a'
# dark_purple='#6c7086'
# "
# kanagawa
set -g @dracula-colors "
white='#dcd7ba'
gray='#2a2a37'
dark_gray='#363646'
light_purple='#363646'
dark_purple='#54546D'
cyan='#6a9589'
green='#938aa9'
orange='#dca561'
red='#e46876'
pink='#d27e99'
yellow='#ff9e3b'
"

set -g @dracula-show-left-icon '#h | #S'

set -g @dracula-military-time false 
set -g @dracula-show-timezone true
set -g @dracula-time-format "#(env LC_ALL=C TZ=America/Los_Angeles date | cut -d' ' -f4-5 | sed 's/:[0-9] [0-9] / /')"
set -g @dracula-git-show-current-symbol '✓'
set -g @dracula-git-show-diff-symbol '!'
set -g @dracula-git-show-remote-status false
set -g @dracula-git-truncate-length 20

set -g @dracula-cpu-usage-label 'CPU'
set -g @dracula-ram-usage-label 'RAM'

set -g @dracula-cwd-max-chars 24

set -g @dracula-uptime-label '↑'

set -g @dracula-show-ssh-only-when-connected true

set -g @dracula-continuum-mode countdown

# tmux-resurrect 
set -g @resurrect-capture-pane-contents 'on'

# tmux-continuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

run '~/.config/tmux/plugins/tpm/tpm'
